#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
#	Accepts 4 command line parameters 
#		The path to the file to be transferred
#		The IP of the server we want to transfer the file to
#		The username scp connects with
#		The path to the SSH private key that scp uses
#	Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed


if [[ "$#" < 3 ]]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~
fi
