#!/usr/bin/env bash
# Bash script that install nginx listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
#+ it will return a page that contains the string Hello World!
sudo apt-get -y install nginx
