#!/usr/bin/env bash
# Bash script that install nginx listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page) using curl,
#+ it will return a page that contains the string Hello World!
#+ Nginx server is configured so that /redirect_me is redirecting to another page
#+ it has a custom 404 page that contains the string Ceci n'est pas une page
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
new_string="\n\t location /redirect_me {\n\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \n\t}\n"
sed -i "53s+.*+$new_string+" /etc/nginx/sites-available/default
mkdir /var/www/error
echo "Ceci n'est pas une page" > /var/www/error/custom_404.html
string_to_be_inserted="\n\terror_page 404 /custom_404.html;\n\n\t\tlocation = /custom_404.html {\n\t\troot /var/www/error;\n\t\tinternal;\n\t}\n"
sed -i "47s+.*+$string_to_be_inserted+" /etc/nginx/sites-available/default
service nginx restart
