#!/usr/bin/env bash
# Install and configure HAproxy on your server

# install HAproxy
apt-get -y update
apt-get -y install haproxy

# configure the frontend
front_end='\\nfrontend first\n\tbind *:80\n\tdefault_backend allservers'
sed -i "34a $front_end" /etc/haproxy/haproxy.cfg

# configure the backend
back_end='\\nbackend allservers\n\tserver 1529-web-01 34.148.38.180\n\tserver 1529-web-02 44.200.179.107'
sed -i "38a $back_end" /etc/haproxy/haproxy.cfg
/etc/init.d/haproxy restart
