#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it
sudo mysqldump -u root --password="$1" --all-databases --master-data > backup.sql
currentDate=$(date +"%Y-%m-%d")
tar -czf "$currentDate".tar.gz backup.sql
