#!/usr/bin/env bash
# Ubuntu container’s Nginx installation

# getting image running ubuntu container
docker run -it ubuntu
apt -y update

# installing nginx, curl, new-tools
apt -y install nginx
apt -y install curl
apt -y install net-tools

# start nginx
service nginx start
