#!/usr/bin/env bash
# Ubuntu container’s Nginx installation

# getting updates
apt -y update

# installing nginx, curl, new-tools
apt -y install nginx
apt -y install curl
apt -y install net-tools

# start nginx
service nginx start
