#!/usr/bin/env bash
# Bash script that:
#+		  Creates the file /var/run/myscript.pid containing its PID
#+		  Displays To infinity and beyond indefinitely
#+		  Displays I hate the kill command when receiving a SIGTERM signal
#+		  Displays Y U no love me?! when receiving a SIGINT signal
#+		  Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid

n=1
file=/var/run/myscript.pid
trap 'rm $file; exit' SIGQUIT SIGTERM

while [ $n -eq 1 ]
do
	echo "To infinity and beyond"
	trap "echo I hate the kill command" SIGTERM
	trap "echo Y U no love me?!" SIGINT
	trap 'rm $file; exit' SIGQUIT SIGTERM
	sleep 2
done
