#!/usr/bin/env bash
# This script parses Apache log access files and display sorted:
#+							       visitor IP along
#+							       HTTP status code

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
