#!/usr/bin/env bash
# Bash script that configures the container to fit
#+ 	nginx that runs as nginx user
#+	nginx listening on all active IPs on port 8080
sed -i "s/nginx/root/" /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
